---

name: Lint Commit message

on:
  push:
  pull_request:

jobs:
  commitlint:
    uses: projectpotos/.github/.github/workflows/commit-lint.yml@main
      with:
        configFile: projectpotos/.github/configs/commitlint.config.js@main
